# Run Label
label: Truncated_PowerlawRedshift_MDC_smoothed_power_law_0
outdir: outdir

# Population Parameters, Models, HyperParameters, and Priors
models:
  python_file: examples/config_files/model.py

# Sampler Configuration Args
sampler:
  kernel: NUTS
  kernel_kwargs:
    dense_mass: true
  mcmc_kwargs:
    num_warmup: 500
    num_samples: 1500
    num_chains: 1

# Data Configuration Args
data:
  catalog_summary_json: /home/bruce.edelman/projects/O4_prep/o4_gwinferno_mdcs/data/smoothed_powerlaw/realization_0/catalog.json
  seminanalytic_injs: true