# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: conda-forge
    - name: Install dependencies 
      run: | # MUST INSTALL NUMPYRO/JAX/JAXLIB WITH PIP: CI FAILS IF INSTALLED WITH CONDA (idfk why)
        conda install flake8 pytest-cov codespell
        conda install pip setuptools
        pip install --upgrade pip
        pip install numpyro 
        pip install -r pip_requirements.txt
        pip install arviz==0.15.1
        pip install scipy==1.11.1
        pre-commit install
    - name: Install GWInferno
      run: |
        pip install .
    - name: List installed
      run: |
        conda list
    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files --verbose --show-diff-on-failure
    - name: Test with pytest
      run: |
        source tests/download_test_data.sh
        pytest --cov gwinferno -ra --color yes --cov-report=xml --junitxml=pytest.xml
    - name: Publish coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.xml
        flags: python${{ matrix.python-version }}
    - name: Coverage report
      run: python -m coverage report --show-missing
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-${{ matrix.python-version }}
        path: pytest.xml
