name: GitHub Pages

permissions:
  contents: write
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          update-conda: true
          python-version: 3.9
          conda-channels: conda-forge

      - name: Install dependencies 
        run: | # MUST INSTALL NUMPYRO/JAX/JAXLIB WITH PIP: CI FAILS IF INSTALLED WITH CONDA (idfk why)
            conda install pip setuptools
            pip install --upgrade pip
            pip install numpyro 
            pip install -r pip_requirements.txt
            pip install -r docs/requirements.txt
            pip install arviz==0.15.1
            pip install scipy==1.11.1
            pip install .

      - name: Build documentation
        run: |
          cd docs
          mv Makefile.gh_pages Makefile
          make clean
          make html
          cd ../
          touch gh-pages/latest/html/.nojekyll
          ls
          ls *
          ls */*
          ls ./gh-pages/latest/html
          rm -r docs
          mv gh-pages/latest/html docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
